"""empty message

Revision ID: 2fb6c1fca2d4
Revises: 4312ca46f744
Create Date: 2016-07-20 11:07:07.072093

"""

# revision identifiers, used by Alembic.
revision = '2fb6c1fca2d4'
down_revision = '4312ca46f744'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_screenshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['product_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_screenshot')
    ### end Alembic commands ###
