"""empty message

Revision ID: 3da6cf7f778c
Revises: None
Create Date: 2016-07-12 12:53:05.388577

"""

# revision identifiers, used by Alembic.
revision = '3da6cf7f778c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_url_created_at'), 'product_url', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_url_domain'), 'product_url', ['domain'], unique=False)
    op.create_index(op.f('ix_product_url_referrer'), 'product_url', ['referrer'], unique=False)
    op.create_index(op.f('ix_product_url_url'), 'product_url', ['url'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_url_url'), table_name='product_url')
    op.drop_index(op.f('ix_product_url_referrer'), table_name='product_url')
    op.drop_index(op.f('ix_product_url_domain'), table_name='product_url')
    op.drop_index(op.f('ix_product_url_created_at'), table_name='product_url')
    op.drop_table('product_url')
    ### end Alembic commands ###
